# Generated by Django 2.2.4 on 2019-09-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_type', models.CharField(max_length=50)),
                ('book_name', models.CharField(max_length=150)),
                ('book_author', models.CharField(max_length=100)),
                ('book_genre', models.CharField(max_length=50)),
                ('book_year', models.CharField(max_length=4)),
                ('book_publications', models.CharField(max_length=100)),
                ('book_pages_count', models.IntegerField()),
                ('book_front_cover', models.ImageField(upload_to='')),
                ('created_date', models.DateTimeField()),
                ('created_by', models.CharField(max_length=10)),
                ('last_modified_date', models.DateTimeField()),
                ('last_modified_by', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'book_master',
            },
        ),
    ]
